### ISSUE TITLE
Question about the loss design.

### ISSUE THREAD

**Issue by SimonX1208** [linhanwang/DC-Gaussian#1]
Thanks for your nice work!

In the code, I can not find the loss item for the sky.
This is different from the description in the paper.
Could you plz tell me  the reason?

![image](https://github.com/user-attachments/assets/785ea643-fa7f-41d5-a8d9-68fb6f55f66d)

**Comment by linhanwang** [comment]
Thanks for your interest. I have not added the sky loss for two reasons. 

1. My original code is really messy because I did a lot of experiments that didn't work. I cleaned the code and rerun all the experiments recently. So this version of code doesn't contain everything in the paper. 

2. The sky loss and G3 Enhancement require extra effort for the users while without these two modules this code can already remove reflections effectively. So due to my limited time budget, I haven't added these two modules. My future plan is to add these two modules in another branch.
 
If you are really interested in the sky loss, you can send me an email. I can share with you my messy version.

**Comment by SimonX1208** [comment]
Thanks for your timely reply!

Through your explanation, I now understand that this version of the code does not include any G3 or sky loss.

However, I am very interested in these components. Could you share them with me via email (simon4time@gmail.com)?

Thank you once again.

**Comment by linhanwang** [comment]
Sent.

**Comment by SimonX1208** [comment]
I got the mail.
Thanks a lot for sharing! @linhanwang

**Comment by 2693748650** [comment]
Hello, I am also very interested in these components of yours. Could you please share them with me via (32309054@mail.imu.edu.cn). Thank you very much.

**Comment by linhanwang** [comment]
Sent.

**Comment by linhanwang** [comment]
Sent

**Comment by Leinadh** [comment]
Hi @linhanwang, I would appreciate if you could also share the code with me (daniel.ibanez@pucp.edu.pe). I'm especially interested in how you used COLMAP and HLoc to preprocess and format the dash cam videos before training the model.
Thank you very much!

**Comment by linhanwang** [comment]
> Hi [@linhanwang](https://github.com/linhanwang), I would appreciate if you could also share the code with me ([daniel.ibanez@pucp.edu.pe](mailto:daniel.ibanez@pucp.edu.pe)). I'm especially interested in how you used COLMAP and HLoc to preprocess and format the dash cam videos before training the model. Thank you very much!

The simplest solution is to use Nerfstudio, which includes built-in support for HLoc and Pixel-Perfect SfM.
